#!/bin/bash
# Copyright Red Hat
#
# git-fix - shortcut for ``git commit --fixup=COMMIT``
#
# This file is part of the snapshot manager project.
#
# SPDX-License-Identifier: Apache-2.0
git commit --fixup $@
