#!/bin/bash
# Copyright Red Hat
#
# git-branchdiff - shortcut for ``git diff main..HEAD``
#
# This file is part of the snapshot manager project.
#
# SPDX-License-Identifier: Apache-2.0
git diff main..HEAD $@
